version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  api:
    container_name: book_api
    build:
      context: ./api
    command: bash -c "cd /api/app && alembic upgrade head && cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api/app:/api/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always