"""Create book model

Revision ID: 35b64a0d7304
Revises: bbb00b216d89
Create Date: 2021-12-23 04:39:05.440659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b64a0d7304'
down_revision = 'bbb00b216d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
